//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichTextBoxExTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichTextBoxExTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;alternate&quot;&gt;
        ///			&lt;td&gt;&lt;img src=&quot;Emoticons%20-%20Yahoo%21%20Messenger_files/24.gif&quot; alt=&quot;rolling on the floor&quot;&gt;&lt;/td&gt;
        ///			&lt;td&gt;&lt;kbd&gt;=))&lt;/kbd&gt;&lt;/td&gt;
        ///			&lt;td class=&quot;description&quot;&gt;&lt;span&gt;rolling on the floor&lt;/span&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr class=&quot;&quot;&gt;
        ///			&lt;td&gt;&lt;img src=&quot;Emoticons%20-%20Yahoo%21%20Messenger_files/25.gif&quot; alt=&quot;angel&quot;&gt;&lt;/td&gt;
        ///			&lt;td&gt;&lt;kbd&gt;O:-)&lt;/kbd&gt;&lt;/td&gt;
        ///			&lt;td class=&quot;description&quot;&gt;&lt;span&gt;angel&lt;/span&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr class=&quot;alternate&quot;&gt;
        ///			&lt;td&gt;&lt;img src=&quot;Emoticons%20-%20Yahoo%21%20Messenger_files/26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yahoo {
            get {
                return ResourceManager.GetString("yahoo", resourceCulture);
            }
        }
    }
}
