// Copyright (C) 2010 OfficeSIP Communications
// This source is subject to the GNU General Public License.
// Please see Notice.txt for details.

using System;

namespace Uccapi
{
    public class Errors
    {
        public const UInt32 UCC_E_CODECS_MISMATCH = 0x80EE0000;
        public const UInt32 UCC_E_STREAM_PRESENT = 0x80EE0001;
        public const UInt32 UCC_E_STREAM_NOT_PRESENT = 0x80EE0002;
        public const UInt32 UCC_E_NO_STREAM = 0x80EE0003;
        public const UInt32 UCC_E_SIP_PARSE_FAILED = 0x80EE0004;
        public const UInt32 UCC_E_SIP_HEADER_NOT_PRESENT = 0x80EE0005;
        public const UInt32 UCC_E_SDP_NOT_PRESENT = 0x80EE0006;
        public const UInt32 UCC_E_SDP_PARSE_FAILED = 0x80EE0007;
        public const UInt32 UCC_E_SDP_UPDATE_FAILED = 0x80EE0008;
        public const UInt32 UCC_E_SDP_MULTICAST = 0x80EE0009;
        public const UInt32 UCC_E_SDP_CONNECTION_ADDR = 0x80EE000A;
        public const UInt32 UCC_E_SDP_NO_MEDIA = 0x80EE000B;
        public const UInt32 UCC_E_SIP_TIMEOUT = 0x80EE000C;
        public const UInt32 UCC_E_SDP_FAILED_TO_BUILD = 0x80EE000D;
        public const UInt32 UCC_E_SIP_INVITE_TRANSACTION_PENDING = 0x80EE000E;
        public const UInt32 UCC_E_SIP_AUTHENTICATION_HEADER_SENT = 0x80EE000F;
        public const UInt32 UCC_E_SIP_AUTHENTICATION_TYPE_NOT_SUPPORTED = 0x80EE0010;
        public const UInt32 UCC_E_SIP_AUTHENTICATION_FAILED = 0x80EE0011;
        public const UInt32 UCC_E_INVALID_SIP_URL = 0x80EE0012;
        public const UInt32 UCC_E_DESTINATION_ADDRESS_LOCAL = 0x80EE0013;
        public const UInt32 UCC_E_INVALID_ADDRESS_LOCAL = 0x80EE0014;
        public const UInt32 UCC_E_DESTINATION_ADDRESS_MULTICAST = 0x80EE0015;
        public const UInt32 UCC_E_INVALID_PROXY_ADDRESS = 0x80EE0016;
        public const UInt32 UCC_E_SIP_TRANSPORT_NOT_SUPPORTED = 0x80EE0017;
        public const UInt32 UCC_E_SIP_NEED_MORE_DATA = 0x80EE0018;
        public const UInt32 UCC_E_SIP_CALL_DISCONNECTED = 0x80EE0019;
        public const UInt32 UCC_E_SIP_REQUEST_DESTINATION_ADDR_NOT_PRESENT = 0x80EE001A;
        public const UInt32 UCC_E_SIP_UDP_SIZE_EXCEEDED = 0x80EE001B;
        public const UInt32 UCC_E_SIP_SSL_TUNNEL_FAILED = 0x80EE001C;
        public const UInt32 UCC_E_SIP_SSL_NEGOTIATION_TIMEOUT = 0x80EE001D;
        public const UInt32 UCC_E_SIP_STACK_SHUTDOWN = 0x80EE001E;
        public const UInt32 UCC_E_MEDIA_CONTROLLER_STATE = 0x80EE001F;
        public const UInt32 UCC_E_MEDIA_NEED_TERMINAL = 0x80EE0020;
        public const UInt32 UCC_E_MEDIA_AUDIO_DEVICE_NOT_AVAILABLE = 0x80EE0021;
        public const UInt32 UCC_E_MEDIA_VIDEO_DEVICE_NOT_AVAILABLE = 0x80EE0022;
        public const UInt32 UCC_E_START_STREAM = 0x80EE0023;
        public const UInt32 UCC_E_MEDIA_AEC = 0x80EE0024;
        public const UInt32 UCC_E_PLATFORM_NOT_INITIALIZED = 0x80EE0025;
        public const UInt32 UCC_E_PLATFORM_ALREADY_INITIALIZED = 0x80EE0026;
        public const UInt32 UCC_E_PLATFORM_ALREADY_SHUT_DOWN = 0x80EE0027;
        public const UInt32 UCC_E_PRESENCE_NOT_ENABLED = 0x80EE0028;
        public const UInt32 UCC_E_INVALID_SESSION_TYPE = 0x80EE0029;
        public const UInt32 UCC_E_INVALID_SESSION_STATE = 0x80EE002A;
        public const UInt32 UCC_E_NO_ENDPOINT = 0x80EE002B;
        public const UInt32 UCC_E_LOCAL_PHONE_NEEDED = 0x80EE002C;
        public const UInt32 UCC_E_NO_DEVICE = 0x80EE002D;
        public const UInt32 UCC_E_INVALID_ENDPOINT = 0x80EE002E;
        public const UInt32 UCC_E_ENDPOINT_NO_PROVISION = 0x80EE002F;
        public const UInt32 UCC_E_ENDPOINT_NO_KEY = 0x80EE0030;
        public const UInt32 UCC_E_ENDPOINT_NO_NAME = 0x80EE0031;
        public const UInt32 UCC_E_ENDPOINT_NO_USER = 0x80EE0032;
        public const UInt32 UCC_E_ENDPOINT_NO_USER_URI = 0x80EE0033;
        public const UInt32 UCC_E_ENDPOINT_NO_SERVER = 0x80EE0034;
        public const UInt32 UCC_E_ENDPOINT_NO_SERVER_ADDRESS = 0x80EE0035;
        public const UInt32 UCC_E_ENDPOINT_NO_SERVER_PROTOCOL = 0x80EE0036;
        public const UInt32 UCC_E_ENDPOINT_INVALID_SERVER_PROTOCOL = 0x80EE0037;
        public const UInt32 UCC_E_ENDPOINT_INVALID_SERVER_AUTHENTICATION_MODE = 0x80EE0038;
        public const UInt32 UCC_E_ENDPOINT_INVALID_SERVER_ROLE = 0x80EE0039;
        public const UInt32 UCC_E_ENDPOINT_MULTIPLE_REGISTRARS = 0x80EE003A;
        public const UInt32 UCC_E_ENDPOINT_INVALID_SESSION = 0x80EE003B;
        public const UInt32 UCC_E_ENDPOINT_INVALID_SESSION_PARTY = 0x80EE003C;
        public const UInt32 UCC_E_ENDPOINT_INVALID_SESSION_TYPE = 0x80EE003D;
        public const UInt32 UCC_E_OPERATION_WITH_TOO_MANY_PARTICIPANTS = 0x80EE003E;
        public const UInt32 UCC_E_BASIC_AUTHENTICATION_SET_TLS = 0x80EE003F;
        public const UInt32 UCC_E_SIP_HIGH_SECURITY_SET_TLS = 0x80EE0040;
        public const UInt32 UCC_S_ROAMING_NOT_SUPPORTED = 0x00EE0041;
        public const UInt32 UCC_E_ENDPOINT_SERVER_UNAUTHORIZED = 0x80EE0042;
        public const UInt32 UCC_E_DUPLICATE_REALM = 0x80EE0043;
        public const UInt32 UCC_E_POLICY_NOT_ALLOW = 0x80EE0044;
        public const UInt32 UCC_E_PORT_MAPPING_UNAVAILABLE = 0x80EE0045;
        public const UInt32 UCC_E_PORT_MAPPING_FAILED = 0x80EE0046;
        public const UInt32 UCC_E_SECURITY_LEVEL_NOT_COMPATIBLE = 0x80EE0047;
        public const UInt32 UCC_E_SECURITY_LEVEL_NOT_DEFINED = 0x80EE0048;
        public const UInt32 UCC_E_SECURITY_LEVEL_NOT_SUPPORTED_BY_PARTICIPANT = 0x80EE0049;
        public const UInt32 UCC_E_DUPLICATE_BUDDY = 0x80EE004A;
        public const UInt32 UCC_E_DUPLICATE_WATCHER = 0x80EE004B;
        public const UInt32 UCC_E_MALFORMED_XML = 0x80EE004C;
        public const UInt32 UCC_E_ROAMING_OPERATION_INTERRUPTED = 0x80EE004D;
        public const UInt32 UCC_E_ROAMING_FAILED = 0x80EE004E;
        public const UInt32 UCC_E_INVALID_BUDDY_LIST = 0x80EE004F;
        public const UInt32 UCC_E_INVALID_ACL_LIST = 0x80EE0050;
        public const UInt32 UCC_E_NO_GROUP = 0x80EE0051;
        public const UInt32 UCC_E_DUPLICATE_GROUP = 0x80EE0052;
        public const UInt32 UCC_E_TOO_MANY_GROUPS = 0x80EE0053;
        public const UInt32 UCC_E_NO_BUDDY = 0x80EE0054;
        public const UInt32 UCC_E_NO_WATCHER = 0x80EE0055;
        public const UInt32 UCC_E_NO_REALM = 0x80EE0056;
        public const UInt32 UCC_E_NO_TRANSPORT = 0x80EE0057;
        public const UInt32 UCC_E_NOT_EXIST = 0x80EE0058;
        public const UInt32 UCC_E_INVALID_PREFERENCE_LIST = 0x80EE0059;
        public const UInt32 UCC_E_MAX_PENDING_OPERATIONS = 0x80EE005A;
        public const UInt32 UCC_E_TOO_MANY_RETRIES = 0x80EE005B;
        public const UInt32 UCC_E_INVALID_PORTRANGE = 0x80EE005C;
        public const UInt32 UCC_E_SIP_CALL_CONNECTION_NOT_ESTABLISHED = 0x80EE005D;
        public const UInt32 UCC_E_SIP_ADDITIONAL_PARTY_IN_TWO_PARTY_SESSION = 0x80EE005E;
        public const UInt32 UCC_E_SIP_PARTY_ALREADY_IN_SESSION = 0x80EE005F;
        public const UInt32 UCC_E_SIP_OTHER_PARTY_JOIN_IN_PROGRESS = 0x80EE0060;
        public const UInt32 UCC_E_INVALID_OBJECT_STATE = 0x80EE0061;
        public const UInt32 UCC_E_PRESENCE_ENABLED = 0x80EE0062;
        public const UInt32 UCC_E_ROAMING_ENABLED = 0x80EE0063;
        public const UInt32 UCC_E_SIP_TLS_INCOMPATIBLE_ENCRYPTION = 0x80EE0064;
        public const UInt32 UCC_E_SIP_INVALID_CERTIFICATE = 0x80EE0065;
        public const UInt32 UCC_E_SIP_DNS_FAIL = 0x80EE0066;
        public const UInt32 UCC_E_SIP_TCP_FAIL = 0x80EE0067;
        public const UInt32 UCC_E_TOO_SMALL_EXPIRES_VALUE = 0x80EE0068;
        public const UInt32 UCC_E_SIP_TLS_FAIL = 0x80EE0069;
        public const UInt32 UCC_E_NOT_PRESENCE_ENDPOINT = 0x80EE006A;
        public const UInt32 UCC_E_SIP_INVITEE_PARTY_TIMEOUT = 0x80EE006B;
        public const UInt32 UCC_E_SIP_AUTHENTICATION_TIME_SKEW = 0x80EE006C;
        public const UInt32 UCC_E_INVALID_REGISTRATION_STATE = 0x80EE006D;
        public const UInt32 UCC_E_MEDIA_DISABLED = 0x80EE006E;
        public const UInt32 UCC_E_MEDIA_ENABLED = 0x80EE006F;
        public const UInt32 UCC_E_REFER_NOT_ACCEPTED = 0x80EE0070;
        public const UInt32 UCC_E_REFER_NOT_ALLOWED = 0x80EE0071;
        public const UInt32 UCC_E_REFER_NOT_EXIST = 0x80EE0072;
        public const UInt32 UCC_E_SIP_HOLD_OPERATION_PENDING = 0x80EE0073;
        public const UInt32 UCC_E_SIP_UNHOLD_OPERATION_PENDING = 0x80EE0074;
        public const UInt32 UCC_E_MEDIA_SESSION_NOT_EXIST = 0x80EE0075;
        public const UInt32 UCC_E_MEDIA_SESSION_IN_HOLD = 0x80EE0076;
        public const UInt32 UCC_E_ANOTHER_MEDIA_SESSION_ACTIVE = 0x80EE0077;
        public const UInt32 UCC_E_MAX_REDIRECTS = 0x80EE0078;
        public const UInt32 UCC_E_REDIRECT_PROCESSING_FAILED = 0x80EE0079;
        public const UInt32 UCC_E_LISTENING_SOCKET_NOT_EXIST = 0x80EE007A;
        public const UInt32 UCC_E_INVALID_LISTEN_SOCKET = 0x80EE007B;
        public const UInt32 UCC_E_PORT_MANAGER_ALREADY_SET = 0x80EE007C;
        public const UInt32 UCC_E_SECURITY_LEVEL_ALREADY_SET = 0x80EE007D;
        public const UInt32 UCC_E_UDP_NOT_SUPPORTED = 0x80EE007E;
        public const UInt32 UCC_E_SIP_REFER_OPERATION_PENDING = 0x80EE007F;
        public const UInt32 UCC_E_PLATFORM_NOT_SUPPORTED = 0x80EE0080;
        public const UInt32 UCC_E_SIP_PEER_PARTICIPANT_IN_MULTIPARTY_SESSION = 0x80EE0081;
        public const UInt32 UCC_E_NOT_ALLOWED = 0x80EE0082;
        public const UInt32 UCC_E_REGISTRATION_DEACTIVATED = 0x80EE0083;
        public const UInt32 UCC_E_REGISTRATION_REJECTED = 0x80EE0084;
        public const UInt32 UCC_E_REGISTRATION_UNREGISTERED = 0x80EE0085;
        public const UInt32 UCC_E_BAD_RLMI_DOCUMENT = 0x80EE0086;
        public const UInt32 UCC_E_INVALID_ID = 0x80EE0087;
        public const UInt32 UCC_E_TRANSIENT_SERVER_DISCONNECT = 0x80EE0088;
        public const UInt32 UCC_E_SIP_AUTHENTICATION_INCORRECT_REALM = 0x80EE0089;
        public const UInt32 UCC_E_ENDPOINT_DUPLICATE_USER_URI_AND_SERVER = 0x80EE008A;
        public const UInt32 UCC_E_CANNOT_ADD_SPECIFIC_DEVICE_TO_SESSION = 0x80EE008B;
        public const UInt32 UCC_E_INVALID_TEL_URL = 0x80EE008C;
        public const UInt32 UCC_E_PHONE_CONTROL_CHANNEL_NOT_EXISTS = 0x80EE008D;
        public const UInt32 UCC_E_3RDPARTY_PHONE_SESSION_EXPECTED = 0x80EE008E;
        public const UInt32 UCC_E_DUPLICATE_3RDPARTY_PHONE_SESSION = 0x80EE008F;
        public const UInt32 UCC_E_CONSULTATION_CALL_IN_PROGRESS = 0x80EE0090;
        public const UInt32 UCC_E_NOT_A_CONSULTATION_CALL = 0x80EE0091;
        public const UInt32 UCC_E_INVALID_OPERATION = 0x80EE0092;
        public const UInt32 UCC_E_RESOURCE_UNAVAILABLE = 0x80EE0093;
        public const UInt32 UCC_E_INCOMPATIBLE_STATE = 0x80EE0094;
        public const UInt32 UCC_E_INSUFFICIENT_SECURITY_LEVEL = 0x80EE0095;
        public const UInt32 UCC_S_TRANSFER_SUCCESS = 0x00EE0096;
        public const UInt32 UCC_S_CONFERENCE_SUCCESS = 0x00EE0097;
        public const UInt32 UCC_S_CONFERENCE_JOIN_SUCCESS = 0x00EE0098;
        public const UInt32 UCC_S_REMOTE_DISCONNECT_SUCCESS = 0x00EE0099;
        public const UInt32 UCC_S_DEFLECT_SUCCESS = 0x00EE009A;
        public const UInt32 UCC_S_FORWARD_DISCONNECT_SUCCESS = 0x00EE009B;
        public const UInt32 UCC_E_T120_NM_CONNECTION_FAILED = 0x80EE009C;
        public const UInt32 UCC_E_NM_ALREADY_RUNNING = 0x80EE009D;
        public const UInt32 UCC_E_RESOURCE_BLOCKED = 0x80EE009E;
        public const UInt32 UCC_E_NOT_A_PRINCIPAL_CALL = 0x80EE009F;
        public const UInt32 UCC_E_PHONE_SERVER_INCAPABLE = 0x80EE00A0;
        public const UInt32 UCC_E_CONF_UNEXPECTED_FAILURE = 0x80EE00A1;
        public const UInt32 UCC_E_NM_INITIALIZATION_FAIL = 0x80EE00A2;
        public const UInt32 UCC_E_INVALID_SERVER_VERSION = 0x80EE00A3;
        public const UInt32 UCC_S_RETRIEVE_SUCCESS = 0x00EE00A4;
        public const UInt32 UCC_E_MEDIA_TYPE_NOT_ALLOWED = 0x80EE00A5;
        public const UInt32 UCC_E_AUTHENTICATION_SERVER_UNAVAILABLE = 0x80EE00A6;
        public const UInt32 UCC_E_DIFFERENT_TRANSPORT_TO_SESSION = 0x80EE00A7;
        public const UInt32 UCC_S_UNSUBSCRIBED_BY_USER = 0x00EE00A8;
        public const UInt32 UCC_E_TERMINATED_BY_SERVER = 0x80EE00A9;
        public const UInt32 UCC_E_IP_ADDRESS_CHANGED = 0x80EE00AA;
        public const UInt32 UCC_E_OUT_OF_ORDER_NOTIFY = 0x80EE00AB;
        public const UInt32 UCC_E_MALFORMED_HEADER_VALUE = 0x80EE00AC;
        public const UInt32 UCC_E_MEDIA_ALLOCATION_FAILED = 0x80EE00AD;
        public const UInt32 UCC_E_REQUEST_CANCELLED = 0x80EE00AE;
        public const UInt32 UCC_E_CONFERENCE_NOT_EXIST = 0x80EE00AF;
        public const UInt32 UCC_E_UNKNOWN_MCU_TYPE = 0x80EE00B0;
        public const UInt32 UCC_E_ANONYMOUS_USERS_NOT_ALLOWED = 0x80EE00B1;
        public const UInt32 UCC_E_CONFERENCE_EXISTS_ALREADY = 0x80EE00B2;
        public const UInt32 UCC_E_FEDERATED_USERS_NOT_ALLOWED = 0x80EE00B3;
        public const UInt32 UCC_E_INVALID_ADMISSION_TYPE = 0x80EE00B4;
        public const UInt32 UCC_E_INVALID_ENCRYPTION_KEY = 0x80EE00B5;
        public const UInt32 UCC_E_INVALID_EXPIRY_TIME = 0x80EE00B6;
        public const UInt32 UCC_E_MCU_TYPE_NOT_AVAILABLE = 0x80EE00B7;
        public const UInt32 UCC_E_MAX_CONFERENCES_EXCEEDED = 0x80EE00B8;
        public const UInt32 UCC_E_MAX_MEETING_SIZE_EXCEEDED = 0x80EE00B9;
        public const UInt32 UCC_E_NOTIFICATION_DATA_TOO_LARGE = 0x80EE00BA;
        public const UInt32 UCC_E_ORGANIZER_ROAMING_DATA_TOO_LARGE = 0x80EE00BB;
        public const UInt32 UCC_E_MEDIA_NOT_SUPPORTED = 0x80EE00BC;
        public const UInt32 UCC_E_TRANSIENT_LOCAL_DISCONNECT = 0x80EE00BD;
        public const UInt32 UCC_S_OPERATION_IN_PROGRESS = 0x00EE00BE;
        public const UInt32 UCC_E_INVALID_SERVER_NAME = 0x80EE00BF;
        public const UInt32 UCC_E_ALREADY_EXIST = 0x80EE00C0;
        public const UInt32 UCC_E_USER_NOT_ANSWERED = 0x80EE00C1;
        public const UInt32 UCC_E_ANOTHER_RECORDING_IN_PROGRESS = 0x80EE00C2;
        public const UInt32 UCC_E_RECORDING_ALREADY_PAUSED = 0x80EE00C3;
        public const UInt32 UCC_E_RECORDING_NOT_PAUSED = 0x80EE00C4;
        public const UInt32 UCC_E_INVALID_SIP_DISPLAY_NAME = 0x80EE00C5;
        public const UInt32 UCC_S_SIP_STATUS_INFO_TRYING = 0x00EF0064;
        public const UInt32 UCC_S_SIP_STATUS_INFO_RINGING = 0x00EF00B4;
        public const UInt32 UCC_S_SIP_STATUS_INFO_CALL_FORWARDING = 0x00EF00B5;
        public const UInt32 UCC_S_SIP_STATUS_INFO_QUEUED = 0x00EF00B6;
        public const UInt32 UCC_S_SIP_STATUS_SESSION_PROGRESS = 0x00EF00B7;
        public const UInt32 UCC_S_SIP_STATUS_SUCCESS = 0x00EF00C8;
        public const UInt32 UCC_S_SIP_STATUS_ACCEPTED = 0x00EF00CA;
        public const UInt32 UCC_E_SIP_STATUS_REDIRECT_MULTIPLE_CHOICES = 0x80EF012C;
        public const UInt32 UCC_E_SIP_STATUS_REDIRECT_MOVED_PERMANENTLY = 0x80EF012D;
        public const UInt32 UCC_E_SIP_STATUS_REDIRECT_MOVED_TEMPORARILY = 0x80EF012E;
        public const UInt32 UCC_E_SIP_STATUS_REDIRECT_SEE_OTHER = 0x80EF012F;
        public const UInt32 UCC_E_SIP_STATUS_REDIRECT_USE_PROXY = 0x80EF0131;
        public const UInt32 UCC_E_SIP_STATUS_REDIRECT_ALTERNATIVE_SERVICE = 0x80EF017C;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_BAD_REQUEST = 0x80EF0190;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_UNAUTHORIZED = 0x80EF0191;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_PAYMENT_REQUIRED = 0x80EF0192;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_FORBIDDEN = 0x80EF0193;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_NOT_FOUND = 0x80EF0194;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_METHOD_NOT_ALLOWED = 0x80EF0195;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_NOT_ACCEPTABLE = 0x80EF0196;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_PROXY_AUTHENTICATION_REQUIRED = 0x80EF0197;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_REQUEST_TIMEOUT = 0x80EF0198;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_CONFLICT = 0x80EF0199;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_GONE = 0x80EF019A;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_LENGTH_REQUIRED = 0x80EF019B;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_REQUEST_ENTITY_TOO_LARGE = 0x80EF019D;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_REQUEST_URI_TOO_LARGE = 0x80EF019E;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_UNSUPPORTED_MEDIA_TYPE = 0x80EF019F;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_BAD_EXTENSION = 0x80EF01A4;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_EXTENSION_REQUIRED = 0x80EF01A5;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_TEMPORARILY_NOT_AVAILABLE = 0x80EF01E0;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_TRANSACTION_DOES_NOT_EXIST = 0x80EF01E1;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_LOOP_DETECTED = 0x80EF01E2;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_TOO_MANY_HOPS = 0x80EF01E3;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_ADDRESS_INCOMPLETE = 0x80EF01E4;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_AMBIGUOUS = 0x80EF01E5;
        public const UInt32 UCC_E_SIP_STATUS_CLIENT_BUSY_HERE = 0x80EF01E6;
        public const UInt32 UCC_E_SIP_STATUS_REQUEST_TERMINATED = 0x80EF01E7;
        public const UInt32 UCC_S_SIP_STATUS_REQUEST_TERMINATED = 0x00EF01E7;
        public const UInt32 UCC_E_SIP_STATUS_NOT_ACCEPTABLE_HERE = 0x80EF01E8;
        public const UInt32 UCC_E_SIP_STATUS_REQUEST_PENDING = 0x80EF01EB;
        public const UInt32 UCC_E_SIP_STATUS_SERVER_INTERNAL_ERROR = 0x80EF01F4;
        public const UInt32 UCC_E_SIP_STATUS_SERVER_NOT_IMPLEMENTED = 0x80EF01F5;
        public const UInt32 UCC_E_SIP_STATUS_SERVER_BAD_GATEWAY = 0x80EF01F6;
        public const UInt32 UCC_E_SIP_STATUS_SERVER_SERVICE_UNAVAILABLE = 0x80EF01F7;
        public const UInt32 UCC_E_SIP_STATUS_SERVER_SERVER_TIMEOUT = 0x80EF01F8;
        public const UInt32 UCC_E_SIP_STATUS_SERVER_VERSION_NOT_SUPPORTED = 0x80EF01F9;
        public const UInt32 UCC_E_SIP_STATUS_MESSAGE_TOO_LARGE = 0x80EF0201;
        public const UInt32 UCC_E_SIP_STATUS_GLOBAL_BUSY_EVERYWHERE = 0x80EF0258;
        public const UInt32 UCC_E_SIP_STATUS_GLOBAL_DECLINE = 0x80EF025B;
        public const UInt32 UCC_E_SIP_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE = 0x80EF025C;
        public const UInt32 UCC_E_SIP_STATUS_GLOBAL_DECLINE_EVERYWHERE = 0x80EF025D;
        public const UInt32 UCC_E_SIP_STATUS_GLOBAL_NOT_ACCEPTABLE = 0x80EF025E;
        public const UInt32 UCC_E_SIP_STATUS_NOT_IN_BATCH = 0x80EF025F;
        public const UInt32 UCC_E_SIP_STATUS_NOT_SUPPORTED = 0x80EF0260;
        public const UInt32 UCC_E_SIP_STATUS_NO_DATA = 0x80EF0261;
        public const UInt32 UCC_E_SIP_STATUS_NOT_MEMBER = 0x80EF0262;
        public const UInt32 UCC_E_SIP_STATUS_RESTART_SESSION = 0x80EF0263;
        public const UInt32 UCC_E_SIP_STATUS_PENDING = 0x80EF0264;

        public static string ToString(int code)
        {
            return ToString((UInt32)code);
        }

        public static string ToString(UInt32 code)
        {
            switch (code)
            {
                case UCC_E_CODECS_MISMATCH: return @"No matching codecs with peer.";
                case UCC_E_STREAM_PRESENT: return @"The stream to be started is already present.";
                case UCC_E_STREAM_NOT_PRESENT: return @"The stream to be stopped is not present.";
                case UCC_E_NO_STREAM: return @"No stream is active.";
                case UCC_E_SIP_PARSE_FAILED: return @"Parsing SIP failed.";
                case UCC_E_SIP_HEADER_NOT_PRESENT: return @"The SIP header is not present in the message.";
                case UCC_E_SDP_NOT_PRESENT: return @"SDP is not present in the SIP message.";
                case UCC_E_SDP_PARSE_FAILED: return @"Parsing SDP failed.";
                case UCC_E_SDP_UPDATE_FAILED: return @"SDP does not match the previous one.";
                case UCC_E_SDP_MULTICAST: return @"Multicast is not supported.";
                case UCC_E_SDP_CONNECTION_ADDR: return @"Media does not contain connection address.";
                case UCC_E_SDP_NO_MEDIA: return @"No media is available for the session.";
                case UCC_E_SIP_TIMEOUT: return @"SIP transaction timed out.";
                case UCC_E_SDP_FAILED_TO_BUILD: return @"Failed to build SDP blob.";
                case UCC_E_SIP_INVITE_TRANSACTION_PENDING: return @"Currently processing another INVITE transaction.";
                case UCC_E_SIP_AUTHENTICATION_HEADER_SENT: return @"Authorization header was sent in a previous request.";
                case UCC_E_SIP_AUTHENTICATION_TYPE_NOT_SUPPORTED: return @"The authentication type requested is not supported.";
                case UCC_E_SIP_AUTHENTICATION_FAILED: return @"Authentication failed.";
                case UCC_E_INVALID_SIP_URL: return @"The SIP URL is not valid.";
                case UCC_E_DESTINATION_ADDRESS_LOCAL: return @"The destination address belongs to the local machine.";
                case UCC_E_INVALID_ADDRESS_LOCAL: return @"The local address is invalid. Check the endpoint.";
                case UCC_E_DESTINATION_ADDRESS_MULTICAST: return @"The destination address is a multicast address.";
                case UCC_E_INVALID_PROXY_ADDRESS: return @"The proxy address is not valid.";
                case UCC_E_SIP_TRANSPORT_NOT_SUPPORTED: return @"The specified transport is not supported.";
                case UCC_E_SIP_NEED_MORE_DATA: return @"Need more data for parsing a whole SIP message.";
                case UCC_E_SIP_CALL_DISCONNECTED: return @"The call has been disconnected.";
                case UCC_E_SIP_REQUEST_DESTINATION_ADDR_NOT_PRESENT: return @"The request destination address is not known.";
                case UCC_E_SIP_UDP_SIZE_EXCEEDED: return @"The sip message size is greater than the UDP message size allowed.";
                case UCC_E_SIP_SSL_TUNNEL_FAILED: return @"Cannot establish SSL tunnel to HTTP proxy.";
                case UCC_E_SIP_SSL_NEGOTIATION_TIMEOUT: return @"Timeout during SSL negotiation.";
                case UCC_E_SIP_STACK_SHUTDOWN: return @"Sip stack is already shutdown.";
                case UCC_E_MEDIA_CONTROLLER_STATE: return @"Operation not allowed in current media controller state.";
                case UCC_E_MEDIA_NEED_TERMINAL: return @"Can not find device.";
                case UCC_E_MEDIA_AUDIO_DEVICE_NOT_AVAILABLE: return @"Audio device is not available.";
                case UCC_E_MEDIA_VIDEO_DEVICE_NOT_AVAILABLE: return @"Video device is not available.";
                case UCC_E_START_STREAM: return @"Can not start stream.";
                case UCC_E_MEDIA_AEC: return @"Failed to enable acoustic echo cancellation.";
                case UCC_E_PLATFORM_NOT_INITIALIZED: return @"Client not initialized.";
                case UCC_E_PLATFORM_ALREADY_INITIALIZED: return @"Client already initialized.";
                case UCC_E_PLATFORM_ALREADY_SHUT_DOWN: return @"Client already shut down.";
                case UCC_E_PRESENCE_NOT_ENABLED: return @"Presence not enabled.";
                case UCC_E_INVALID_SESSION_TYPE: return @"Invalid session type.";
                case UCC_E_INVALID_SESSION_STATE: return @"Invalid session state.";
                case UCC_E_NO_ENDPOINT: return @"No valid endpoint for this operation.";
                case UCC_E_LOCAL_PHONE_NEEDED: return @"A local phone number is needed.";
                case UCC_E_NO_DEVICE: return @"No preferred device.";
                case UCC_E_INVALID_ENDPOINT: return @"Invalid endpoint.";
                case UCC_E_ENDPOINT_NO_PROVISION: return @"No provision tag in endpoint.";
                case UCC_E_ENDPOINT_NO_KEY: return @"No endpoint key.";
                case UCC_E_ENDPOINT_NO_NAME: return @"No endpoint name.";
                case UCC_E_ENDPOINT_NO_USER: return @"No user tag in endpoint.";
                case UCC_E_ENDPOINT_NO_USER_URI: return @"No user URI in endpoint.";
                case UCC_E_ENDPOINT_NO_SERVER: return @"No server tag in endpoint.";
                case UCC_E_ENDPOINT_NO_SERVER_ADDRESS: return @"Server tag missing address in endpoint.";
                case UCC_E_ENDPOINT_NO_SERVER_PROTOCOL: return @"Server tag missing protocol in endpoint.";
                case UCC_E_ENDPOINT_INVALID_SERVER_PROTOCOL: return @"Invalid server protocol in endpoint.";
                case UCC_E_ENDPOINT_INVALID_SERVER_AUTHENTICATION_MODE: return @"Invalid server authentication method in endpoint.";
                case UCC_E_ENDPOINT_INVALID_SERVER_ROLE: return @"Invalid server role in endpoint.";
                case UCC_E_ENDPOINT_MULTIPLE_REGISTRARS: return @"Multiple registrar servers in endpoint.";
                case UCC_E_ENDPOINT_INVALID_SESSION: return @"Invalid session tag in endpoint.";
                case UCC_E_ENDPOINT_INVALID_SESSION_PARTY: return @"Invalid session party in endpoint.";
                case UCC_E_ENDPOINT_INVALID_SESSION_TYPE: return @"Invalid session type in endpoint.";
                case UCC_E_OPERATION_WITH_TOO_MANY_PARTICIPANTS: return @"The operation failed because of too many participants in the session.";
                case UCC_E_BASIC_AUTHENTICATION_SET_TLS: return @"Must set transport to TLS if Basic Auth is allowed.";
                case UCC_E_SIP_HIGH_SECURITY_SET_TLS: return @"Must set transport to TLS if high security mode is needed.";
                case UCC_S_ROAMING_NOT_SUPPORTED: return @"Server does not support this type of roaming.";
                case UCC_E_ENDPOINT_SERVER_UNAUTHORIZED: return @"Server address does not match an authorized domain in endpoint.";
                case UCC_E_DUPLICATE_REALM: return @"Duplicate realm exists in an enabled endpoint.";
                case UCC_E_POLICY_NOT_ALLOW: return @"Current policy settings do not allow this action.";
                case UCC_E_PORT_MAPPING_UNAVAILABLE: return @"Port mapping can not be obtained from the port manager.";
                case UCC_E_PORT_MAPPING_FAILED: return @"Port mapping failure returned from the port manager.";
                case UCC_E_SECURITY_LEVEL_NOT_COMPATIBLE: return @"The local and remote security levels are not compatible.";
                case UCC_E_SECURITY_LEVEL_NOT_DEFINED: return @"The security level is not defined.";
                case UCC_E_SECURITY_LEVEL_NOT_SUPPORTED_BY_PARTICIPANT: return @"Participant could not support the requested security level.";
                case UCC_E_DUPLICATE_BUDDY: return @"Contact already exists.";
                case UCC_E_DUPLICATE_WATCHER: return @"Watcher already exists.";
                case UCC_E_MALFORMED_XML: return @"Malformed XML.";
                case UCC_E_ROAMING_OPERATION_INTERRUPTED: return @"Roaming operation interrupted. It may still succeed or fail.";
                case UCC_E_ROAMING_FAILED: return @"Roaming session failed.";
                case UCC_E_INVALID_BUDDY_LIST: return @"Contact list is invalid.";
                case UCC_E_INVALID_ACL_LIST: return @"ACL list is invalid.";
                case UCC_E_NO_GROUP: return @"Group does not exist.";
                case UCC_E_DUPLICATE_GROUP: return @"Group already exists.";
                case UCC_E_TOO_MANY_GROUPS: return @"Max number of groups has been reached.";
                case UCC_E_NO_BUDDY: return @"Contact does not exist.";
                case UCC_E_NO_WATCHER: return @"Watcher does not exist.";
                case UCC_E_NO_REALM: return @"No realm is set.";
                case UCC_E_NO_TRANSPORT: return @"Server can not be specified without a transport protocol.";
                case UCC_E_NOT_EXIST: return @"The required item does not exist.";
                case UCC_E_INVALID_PREFERENCE_LIST: return @"Preference list is invalid.";
                case UCC_E_MAX_PENDING_OPERATIONS: return @"Maximum number of pending operations reached.";
                case UCC_E_TOO_MANY_RETRIES: return @"Too many attempts to resend a request.";
                case UCC_E_INVALID_PORTRANGE: return @"Invalid port range.";
                case UCC_E_SIP_CALL_CONNECTION_NOT_ESTABLISHED: return @"Call connection has not been established.";
                case UCC_E_SIP_ADDITIONAL_PARTY_IN_TWO_PARTY_SESSION: return @"Adding additional parties to two party session failed.";
                case UCC_E_SIP_PARTY_ALREADY_IN_SESSION: return @"Party already exists in session.";
                case UCC_E_SIP_OTHER_PARTY_JOIN_IN_PROGRESS: return @"Join operation is in progress for another party.";
                case UCC_E_INVALID_OBJECT_STATE: return @"Object state does not allow to perform this operation.";
                case UCC_E_PRESENCE_ENABLED: return @"Presence is enabled.";
                case UCC_E_ROAMING_ENABLED: return @"Roaming is enabled.";
                case UCC_E_SIP_TLS_INCOMPATIBLE_ENCRYPTION: return @"Incompatible TLS encryption.";
                case UCC_E_SIP_INVALID_CERTIFICATE: return @"Invalid certificate.";
                case UCC_E_SIP_DNS_FAIL: return @"DNS lookup fails.";
                case UCC_E_SIP_TCP_FAIL: return @"Fails to make a TCP connection.";
                case UCC_E_TOO_SMALL_EXPIRES_VALUE: return @"Expiration value received from the server is too small.";
                case UCC_E_SIP_TLS_FAIL: return @"Fails to make a TLS connection.";
                case UCC_E_NOT_PRESENCE_ENDPOINT: return @"A presence endpoint must be used.";
                case UCC_E_SIP_INVITEE_PARTY_TIMEOUT: return @"Invitee connection fails.";
                case UCC_E_SIP_AUTHENTICATION_TIME_SKEW: return @"Authentication failure because of time skew between client and server.";
                case UCC_E_INVALID_REGISTRATION_STATE: return @"Invalid registration state.";
                case UCC_E_MEDIA_DISABLED: return @"Media is disabled.";
                case UCC_E_MEDIA_ENABLED: return @"Media is enabled.";
                case UCC_E_REFER_NOT_ACCEPTED: return @"Refer has not been accepted.";
                case UCC_E_REFER_NOT_ALLOWED: return @"Refer operation is not allowed in this session.";
                case UCC_E_REFER_NOT_EXIST: return @"Refer session does not exist or has finished.";
                case UCC_E_SIP_HOLD_OPERATION_PENDING: return @"Currently a hold operation is pending.";
                case UCC_E_SIP_UNHOLD_OPERATION_PENDING: return @"Currently an unhold operation is pending.";
                case UCC_E_MEDIA_SESSION_NOT_EXIST: return @"Media session does not exist.";
                case UCC_E_MEDIA_SESSION_IN_HOLD: return @"Media session is in hold.";
                case UCC_E_ANOTHER_MEDIA_SESSION_ACTIVE: return @"Another media session is active.";
                case UCC_E_MAX_REDIRECTS: return @"Too many redirects.";
                case UCC_E_REDIRECT_PROCESSING_FAILED: return @"Processing redirect failed.";
                case UCC_E_LISTENING_SOCKET_NOT_EXIST: return @"Listening socket does not exist.";
                case UCC_E_INVALID_LISTEN_SOCKET: return @"Specified address and port is invalid.";
                case UCC_E_PORT_MANAGER_ALREADY_SET: return @"Port manager already set.";
                case UCC_E_SECURITY_LEVEL_ALREADY_SET: return @"The security level has already been set for this Media type can and can not be changed.";
                case UCC_E_UDP_NOT_SUPPORTED: return @"This feature is not supported when one of the server in endpoint has UDP transport.";
                case UCC_E_SIP_REFER_OPERATION_PENDING: return @"Currently a refer operation is pending.";
                case UCC_E_PLATFORM_NOT_SUPPORTED: return @"This operation is not supported on this Windows platform.";
                case UCC_E_SIP_PEER_PARTICIPANT_IN_MULTIPARTY_SESSION: return @"A peer participant cannot be added to a multiparty session.";
                case UCC_E_NOT_ALLOWED: return @"This action is not allowed.";
                case UCC_E_REGISTRATION_DEACTIVATED: return @"The user is being moved.";
                case UCC_E_REGISTRATION_REJECTED: return @"The user's account was disabled or deleted or the SIP URI changed.";
                case UCC_E_REGISTRATION_UNREGISTERED: return @"The user was logged out because the user logged in elsewhere.";
                case UCC_E_BAD_RLMI_DOCUMENT: return @"The RLMI document is invalid.";
                case UCC_E_INVALID_ID: return @"The device ID is invalid.";
                case UCC_E_TRANSIENT_SERVER_DISCONNECT: return @"This operation failed because the server is unreachable or busy at this time. Please try again later.";
                case UCC_E_SIP_AUTHENTICATION_INCORRECT_REALM: return @"Authentication failed because realm value in incoming message does not match realm value stored in endpoint.";
                case UCC_E_ENDPOINT_DUPLICATE_USER_URI_AND_SERVER: return @"An endpoint with the same User URI and SIP Server is already enabled.";
                case UCC_E_CANNOT_ADD_SPECIFIC_DEVICE_TO_SESSION: return @"Cannot add a specific device to a session.";
                case UCC_E_INVALID_TEL_URL: return @"The TEL URL is not valid.";
                case UCC_E_PHONE_CONTROL_CHANNEL_NOT_EXISTS: return @"The phone control channel does not exist.";
                case UCC_E_3RDPARTY_PHONE_SESSION_EXPECTED: return @"3rd-party phone control session expected.";
                case UCC_E_DUPLICATE_3RDPARTY_PHONE_SESSION: return @"3rd-party phone control session with the same call-ID exists.";
                case UCC_E_CONSULTATION_CALL_IN_PROGRESS: return @"Consultation call is already in progress.";
                case UCC_E_NOT_A_CONSULTATION_CALL: return @"Operation is allowed only on consultation call which is not the case here.";
                case UCC_E_INVALID_OPERATION: return @"Performed operation is neither valid nor allowed.";
                case UCC_E_RESOURCE_UNAVAILABLE: return @"A required resource is not available.";
                case UCC_E_INCOMPATIBLE_STATE: return @"Performed operation is not compatible with current object state.";
                case UCC_E_INSUFFICIENT_SECURITY_LEVEL: return @"Session was rejected due to insufficient security level.";
                case UCC_S_TRANSFER_SUCCESS: return @"Transfer operation successful.";
                case UCC_S_CONFERENCE_SUCCESS: return @"Conference operation successful.";
                case UCC_S_CONFERENCE_JOIN_SUCCESS: return @"Conference-join operation successful.";
                case UCC_S_REMOTE_DISCONNECT_SUCCESS: return @"Remote disconnect operation successful.";
                case UCC_S_DEFLECT_SUCCESS: return @"Remote disconnect operation successful.";
                case UCC_S_FORWARD_DISCONNECT_SUCCESS: return @"Disconnected due to forwarding operation.";
                case UCC_E_T120_NM_CONNECTION_FAILED: return @"T120 NetMeeting connection failed.";
                case UCC_E_NM_ALREADY_RUNNING: return @"NetMeeting is already running.";
                case UCC_E_RESOURCE_BLOCKED: return @"A required resource is blocked.";
                case UCC_E_NOT_A_PRINCIPAL_CALL: return @"Operation is allowed only on a principal call which is not the case here.";
                case UCC_E_PHONE_SERVER_INCAPABLE: return @"The 3PCC server does not support basic operations.";
                case UCC_E_CONF_UNEXPECTED_FAILURE: return @"Unexpected failure occured in the conference session.";
                case UCC_E_NM_INITIALIZATION_FAIL: return @"NetMeeting initialization failed.";
                case UCC_E_INVALID_SERVER_VERSION: return @"Server version received from the server is invalid.";
                case UCC_S_RETRIEVE_SUCCESS: return @"Server version received from the server is invalid.";
                case UCC_E_MEDIA_TYPE_NOT_ALLOWED: return @"Remote party does not support this media type.";
                case UCC_E_AUTHENTICATION_SERVER_UNAVAILABLE: return @"Authenticating server cannot be reached.";
                case UCC_E_DIFFERENT_TRANSPORT_TO_SESSION: return @"All participants in a session must have the same transport. Cannot add a participant with a different transport to a session.";
                case UCC_S_UNSUBSCRIBED_BY_USER: return @"This subscription has been terminated due to user action.";
                case UCC_E_TERMINATED_BY_SERVER: return @"The subscription was unexpectedly terminated by the server.";
                case UCC_E_IP_ADDRESS_CHANGED: return @"Client IP address has changed. New IP address may not be immediately available.";
                case UCC_E_OUT_OF_ORDER_NOTIFY: return @"Received an out of order notify message from server.";
                case UCC_E_MALFORMED_HEADER_VALUE: return @"Header value supplied was malformed.";
                case UCC_E_MEDIA_ALLOCATION_FAILED: return @"Media port allocation failed.";
                case UCC_E_REQUEST_CANCELLED: return @"Request was cancelled.";
                case UCC_E_CONFERENCE_NOT_EXIST: return @"Conference doesn't exist.";
                case UCC_E_UNKNOWN_MCU_TYPE: return @"Unknown MCU type.";
                case UCC_E_ANONYMOUS_USERS_NOT_ALLOWED: return @"Anonymous users not allowed.";
                case UCC_E_CONFERENCE_EXISTS_ALREADY: return @"Conference already exists. Possible duplicate conference ID.";
                case UCC_E_FEDERATED_USERS_NOT_ALLOWED: return @"Federated users not allowed.";
                case UCC_E_INVALID_ADMISSION_TYPE: return @"Invalid conference admission type.";
                case UCC_E_INVALID_ENCRYPTION_KEY: return @"Invalid encryption key.";
                case UCC_E_INVALID_EXPIRY_TIME: return @"Invalid conference expiry time.";
                case UCC_E_MCU_TYPE_NOT_AVAILABLE: return @"MCU type not available.";
                case UCC_E_MAX_CONFERENCES_EXCEEDED: return @"Maximum number of conferences exceeded.";
                case UCC_E_MAX_MEETING_SIZE_EXCEEDED: return @"Maximum meeting size exceeded.";
                case UCC_E_NOTIFICATION_DATA_TOO_LARGE: return @"Conference participant notification data too large.";
                case UCC_E_ORGANIZER_ROAMING_DATA_TOO_LARGE: return @"Conference organizer roaming data too large.";
                case UCC_E_MEDIA_NOT_SUPPORTED: return @"Media not supported.";
                case UCC_E_TRANSIENT_LOCAL_DISCONNECT: return @"This operation failed because the network is unavailable at this time. Please try again later.";
                case UCC_S_OPERATION_IN_PROGRESS: return @"The operation is in progress.";
                case UCC_E_INVALID_SERVER_NAME: return @"The specified server name is invalid.";
                case UCC_E_ALREADY_EXIST: return @"The specified item already exists.";
                case UCC_E_USER_NOT_ANSWERED: return @"The user didn't answer the call.";
                case UCC_E_ANOTHER_RECORDING_IN_PROGRESS: return @"Another recording already in progress.";
                case UCC_E_RECORDING_ALREADY_PAUSED: return @"Recording already paused.";
                case UCC_E_RECORDING_NOT_PAUSED: return @"Recording not paused.";
                case UCC_E_INVALID_SIP_DISPLAY_NAME: return @"The SIP display name contains invalid characters.";
                case UCC_S_SIP_STATUS_INFO_TRYING: return @"SIP status code: 100 Trying.";
                case UCC_S_SIP_STATUS_INFO_RINGING: return @"SIP status code: 180 Ringing.";
                case UCC_S_SIP_STATUS_INFO_CALL_FORWARDING: return @"SIP status code: 181 Call Is Being Forwarded.";
                case UCC_S_SIP_STATUS_INFO_QUEUED: return @"SIP status code: 182 Queued";
                case UCC_S_SIP_STATUS_SESSION_PROGRESS: return @"SIP status code: 183 Session Progress.";
                case UCC_S_SIP_STATUS_SUCCESS: return @"SIP status code: 200 OK.";
                case UCC_S_SIP_STATUS_ACCEPTED: return @"SIP status code: 202 Accepted.";
                case UCC_E_SIP_STATUS_REDIRECT_MULTIPLE_CHOICES: return @"SIP status code: 300 Multiple Choices.";
                case UCC_E_SIP_STATUS_REDIRECT_MOVED_PERMANENTLY: return @"SIP status code: 301 Moved Permanently.";
                case UCC_E_SIP_STATUS_REDIRECT_MOVED_TEMPORARILY: return @"SIP status code: 302 Moved Temporarily.";
                case UCC_E_SIP_STATUS_REDIRECT_SEE_OTHER: return @"SIP status code: 303 See Other.";
                case UCC_E_SIP_STATUS_REDIRECT_USE_PROXY: return @"SIP status code: 305 Use Proxy.";
                case UCC_E_SIP_STATUS_REDIRECT_ALTERNATIVE_SERVICE: return @"SIP status code: 380 Alternative Service.";
                case UCC_E_SIP_STATUS_CLIENT_BAD_REQUEST: return @"SIP status code: 400 Bad Request.";
                case UCC_E_SIP_STATUS_CLIENT_UNAUTHORIZED: return @"SIP status code: 401 Unauthorized.";
                case UCC_E_SIP_STATUS_CLIENT_PAYMENT_REQUIRED: return @"SIP status code: 402 Payment Required.";
                case UCC_E_SIP_STATUS_CLIENT_FORBIDDEN: return @"SIP status code: 403 Forbidden.";
                case UCC_E_SIP_STATUS_CLIENT_NOT_FOUND: return @"SIP status code: 404 Not Found.";
                case UCC_E_SIP_STATUS_CLIENT_METHOD_NOT_ALLOWED: return @"SIP status code: 405 Method Not Allowed.";
                case UCC_E_SIP_STATUS_CLIENT_NOT_ACCEPTABLE: return @"SIP status code: 406 Not Acceptable.";
                case UCC_E_SIP_STATUS_CLIENT_PROXY_AUTHENTICATION_REQUIRED: return @"SIP status code: 407 Proxy Authentication Required.";
                case UCC_E_SIP_STATUS_CLIENT_REQUEST_TIMEOUT: return @"SIP status code: 408 Request Timeout.";
                case UCC_E_SIP_STATUS_CLIENT_CONFLICT: return @"SIP status code: 409 Conflict.";
                case UCC_E_SIP_STATUS_CLIENT_GONE: return @"SIP status code: 410 Gone.";
                case UCC_E_SIP_STATUS_CLIENT_LENGTH_REQUIRED: return @"SIP status code: 411 Length Required.";
                case UCC_E_SIP_STATUS_CLIENT_REQUEST_ENTITY_TOO_LARGE: return @"SIP status code: 413 Request Entity Too Large.";
                case UCC_E_SIP_STATUS_CLIENT_REQUEST_URI_TOO_LARGE: return @"SIP status code: 414 Request-URI Too Long.";
                case UCC_E_SIP_STATUS_CLIENT_UNSUPPORTED_MEDIA_TYPE: return @"SIP status code: 415 Unsupported Media Type.";
                case UCC_E_SIP_STATUS_CLIENT_BAD_EXTENSION: return @"SIP status code: 420 Bad Extension.";
                case UCC_E_SIP_STATUS_CLIENT_EXTENSION_REQUIRED: return @"SIP status code: 421 Extension Required.";
                case UCC_E_SIP_STATUS_CLIENT_TEMPORARILY_NOT_AVAILABLE: return @"SIP status code: 480 Temporarily Unavailable.";
                case UCC_E_SIP_STATUS_CLIENT_TRANSACTION_DOES_NOT_EXIST: return @"SIP status code: 481 Call Leg/Transaction Does Not Exist.";
                case UCC_E_SIP_STATUS_CLIENT_LOOP_DETECTED: return @"SIP status code: 482 Loop Detected.";
                case UCC_E_SIP_STATUS_CLIENT_TOO_MANY_HOPS: return @"SIP status code: 483 Too Many Hops.";
                case UCC_E_SIP_STATUS_CLIENT_ADDRESS_INCOMPLETE: return @"SIP status code: 484 Address Incomplete.";
                case UCC_E_SIP_STATUS_CLIENT_AMBIGUOUS: return @"SIP status code: 485 Ambiguous.";
                case UCC_E_SIP_STATUS_CLIENT_BUSY_HERE: return @"SIP status code: 486 Busy Here.";
                case UCC_E_SIP_STATUS_REQUEST_TERMINATED: return @"SIP status code: 487 Request Terminated.";
                case UCC_S_SIP_STATUS_REQUEST_TERMINATED: return @"SIP status code: 487 Request Terminated.";
                case UCC_E_SIP_STATUS_NOT_ACCEPTABLE_HERE: return @"SIP status code: 488 Not Acceptable Here.";
                case UCC_E_SIP_STATUS_REQUEST_PENDING: return @"SIP status code: 491 Request Pending.";
                case UCC_E_SIP_STATUS_SERVER_INTERNAL_ERROR: return @"SIP status code: 500 Server Internal Error.";
                case UCC_E_SIP_STATUS_SERVER_NOT_IMPLEMENTED: return @"SIP status code: 501 Not Implemented.";
                case UCC_E_SIP_STATUS_SERVER_BAD_GATEWAY: return @"SIP status code: 502 Bad Gateway.";
                case UCC_E_SIP_STATUS_SERVER_SERVICE_UNAVAILABLE: return @"SIP status code: 503 Service Unavailable.";
                case UCC_E_SIP_STATUS_SERVER_SERVER_TIMEOUT: return @"SIP status code: 504 Server Time-out.";
                case UCC_E_SIP_STATUS_SERVER_VERSION_NOT_SUPPORTED: return @"SIP status code: 505 Version Not Supported.";
                case UCC_E_SIP_STATUS_MESSAGE_TOO_LARGE: return @"SIP status code: 513 Message Too Large.";
                case UCC_E_SIP_STATUS_GLOBAL_BUSY_EVERYWHERE: return @"SIP status code: 600 Busy Everywhere.";
                case UCC_E_SIP_STATUS_GLOBAL_DECLINE: return @"SIP status code: 603 Decline.";
                case UCC_E_SIP_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE: return @"SIP status code: 604 Does Not Exist Anywhere.";
                case UCC_E_SIP_STATUS_GLOBAL_DECLINE_EVERYWHERE: return @"SIP status code: 605 Decline Everywhere.";
                case UCC_E_SIP_STATUS_GLOBAL_NOT_ACCEPTABLE: return @"SIP status code: 606 Not Acceptable.";
                case UCC_E_SIP_STATUS_NOT_IN_BATCH: return @"SIP status code: 607 Not In Batch.";
                case UCC_E_SIP_STATUS_NOT_SUPPORTED: return @"SIP status code: 608 Not Supported.";
                case UCC_E_SIP_STATUS_NO_DATA: return @"SIP status code: 609 No Data.";
                case UCC_E_SIP_STATUS_NOT_MEMBER: return @"SIP status code: 610 Not Member.";
                case UCC_E_SIP_STATUS_RESTART_SESSION: return @"SIP status code: 611 Restart Session.";
                case UCC_E_SIP_STATUS_PENDING: return @"SIP status code: 612 Pending.";
            }
            return @"";
        }
    }
}
