using System;

namespace Microsoft.Win32.Ssp
{
	public enum SecurityStatus : uint
	{
		SEC_E_OK,
		SEC_E_INSUFFICIENT_MEMORY = 2148074240u,
		SEC_E_INVALID_HANDLE,
		SEC_E_UNSUPPORTED_FUNCTION,
		SEC_E_TARGET_UNKNOWN,
		SEC_E_INTERNAL_ERROR,
		SEC_E_SECPKG_NOT_FOUND,
		SEC_E_NOT_OWNER,
		SEC_E_CANNOT_INSTALL,
		SEC_E_INVALID_TOKEN,
		SEC_E_CANNOT_PACK,
		SEC_E_QOP_NOT_SUPPORTED,
		SEC_E_NO_IMPERSONATION,
		SEC_E_LOGON_DENIED,
		SEC_E_UNKNOWN_CREDENTIALS,
		SEC_E_NO_CREDENTIALS,
		SEC_E_MESSAGE_ALTERED,
		SEC_E_OUT_OF_SEQUENCE,
		SEC_E_NO_AUTHENTICATING_AUTHORITY,
		SEC_I_CONTINUE_NEEDED = 590610u,
		SEC_I_COMPLETE_NEEDED,
		SEC_I_COMPLETE_AND_CONTINUE,
		SEC_I_LOCAL_LOGON,
		SEC_E_BAD_PKGID = 2148074262u,
		SEC_E_CONTEXT_EXPIRED,
		SEC_E_INCOMPLETE_MESSAGE,
		SEC_E_INCOMPLETE_CREDENTIALS = 2148074272u,
		SEC_E_BUFFER_TOO_SMALL,
		SEC_I_INCOMPLETE_CREDENTIALS = 590624u,
		SEC_I_RENEGOTIATE,
		SEC_E_WRONG_PRINCIPAL = 2148074274u,
		SEC_E_ALGORITHM_MISMATCH = 2148074289u,
		SEC_E_ENCRYPT_FAILURE = 2148074281u,
		SEC_E_DECRYPT_FAILURE = 2148074288u,
		SEC_E_UNKNOW_ERROR = 4294967295u
	}
}
