using System;

namespace Microsoft.Win32.Ssp
{
	public enum UlAttribute
	{
		SECPKG_ATTR_SIZES,
		SECPKG_ATTR_NAMES,
		SECPKG_ATTR_LIFESPAN,
		SECPKG_ATTR_DCE_INFO,
		SECPKG_ATTR_STREAM_SIZES,
		SECPKG_ATTR_KEY_INFO,
		SECPKG_ATTR_AUTHORITY,
		SECPKG_ATTR_PROTO_INFO,
		SECPKG_ATTR_PASSWORD_EXPIRY,
		SECPKG_ATTR_SESSION_KEY,
		SECPKG_ATTR_PACKAGE_INFO,
		SECPKG_ATTR_USER_FLAGS,
		SECPKG_ATTR_NEGOTIATION_INFO,
		SECPKG_ATTR_NATIVE_NAMES,
		SECPKG_ATTR_FLAGS,
		SECPKG_ATTR_USE_VALIDATED,
		SECPKG_ATTR_CREDENTIAL_NAME,
		SECPKG_ATTR_TARGET_INFORMATION,
		SECPKG_ATTR_ACCESS_TOKEN,
		SECPKG_ATTR_TARGET,
		SECPKG_ATTR_AUTHENTICATION_ID,
		SECPKG_ATTR_LOGOFF_TIME
	}
}
