using System;

namespace Sip.Message
{
	public enum StatusCodes
	{
		None = -1,
		Trying = 100,
		Ringing = 180,
		CallIsBeingForwarded,
		Queued,
		SessionProgress,
		OK = 200,
		MultipleChoices = 300,
		MovedPermanently,
		MovedTemporarily,
		UseProxy = 305,
		AlternativeService = 380,
		BadRequest = 400,
		Unauthorized,
		PaymentRequired,
		Forbidden,
		NotFound,
		MethodNotAllowed,
		NotAcceptable,
		ProxyAuthenticationRequired,
		RequestTimeout,
		Gone = 410,
		RequestEntityTooLarge = 413,
		RequestURITooLarge,
		UnsupportedMediaType,
		UnsupportedURIScheme,
		BadExtension = 420,
		ExtensionRequired,
		IntervalTooBrief = 423,
		TemporarilyUnavailable = 480,
		CallLegTransactionDoesNotExist,
		LoopDetected,
		TooManyHops,
		AddressIncomplete,
		Ambiguous,
		BusyHere,
		RequestTerminated,
		NotAcceptableHere,
		RequestPending = 491,
		Undecipherable = 493,
		InternalServerError = 500,
		NotImplemented,
		BadGateway,
		ServiceUnavailable,
		ServerTimeOut,
		SipVersionNotSupported,
		MessageTooLarge = 513,
		BusyEverywhere = 600,
		Decline = 603,
		DoesNotExistAnywhere
	}
}
